// menu items
const menu = [
    {
        id: 1,
        title: "buttermilk pancakes",
        price: 15.99,
        img: "./images/item_1.jpg",
        desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
    },
    {
        id: 2,
        title: "Godzilla Milkshake",
        price: 6.99,
        img: "./images/item_2.jpg",
        desc: "ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.",
    },
    {
        id: 3,
        title: "Egg Attack",
        price: 15.99,
        img: "./images/item_3.jpg",
        desc: "franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up",
    },
    {
        id: 4,
        title: "Bacon Overflow",
        price: 8.99,
        img: "./images/item_4.jpg",
        desc: "carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird",
    },
    {
        id: 5,
        title: "Shakes Buddy",
        price: 16.99,
        img: "./images/item_5.jpg",
        desc: "skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.",
    },
    {
        id: 6,
        title: "Diner Double",
        price: 15.99,
        img: "./images/item_6.jpg",
        desc: "vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        id: 7,
        title: "Grilled Fire Steak",
        price: 20.99,
        img: "./images/item_7.jpg",
        desc: "This boneless steak is cut from the centre of the Rib Steak and is considered one of the five most tender meat cuts. It has a reputation for being the most marbles and delivers intense meat flavour and tenderness. Fast cooking and convenient, grilling steaks are tender by nature and always delicious.",
    },
    {
        id: 8,
        title: "Oreo Dream",
        price: 18.99,
        img: "./images/item_8.jpg",
        desc: "Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday",
    },
    {
        id: 9,
        title: "Naruto Special",
        price: 14.99,
        img: "./images/item_9.jpg",
        desc: "Japanese noodle dish. It consists of Chinese-style wheat noodles served in a meat-based broth, often flavored with soy sauce or miso, and uses toppings such as sliced pork, nori, menma, and scallions",
    },
    // {
    //     id:,
    //     title: "",
    //     price:,
    //     img: "./images/item_3.jpg",
    //     desc: "",
    // },
    // {
    //     id:,
    //     title: "",
    //     price:,
    //     img: "./images/item_3.jpg",
    //     desc: "",
    // },
];